{
 "title": "Event Stream Processing",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Count of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  action AS metric,\n  count\nFROM computed_data\nWHERE\n  $__timeFilter(event_time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Count of errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  action AS metric,\n  count_is_error\nFROM computed_data\nWHERE\n  $__timeFilter(event_time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Errors/Requests ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  action AS metric,\n  (count_is_error::FLOAT/count::FLOAT) \nFROM computed_data\nWHERE\n  $__timeFilter(event_time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Avg durations of requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  action AS metric,\n  avg_duration_ms/1000\nFROM computed_data\nWHERE\n  $__timeFilter(event_time)\nORDER BY 1,2"
    }
   ]
  }
 ]
}